version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy

#permissions:
#  - object: /home/ec2-user/app/deploy/
#    owner: ubuntu
#    group: ubuntu
#    mode: 755

hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root